document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'ie=edge\'>");
document.writeln("    <title>Document</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("    <div class=\'header\'>");
document.writeln("        <div class=\'header-top\'>");
document.writeln("            <div class=\'content\'>");
document.writeln("                您好，欢迎来到潮男购物网站！");
document.writeln("                <div class=\'header-top-right\'>");
document.writeln("                    <a rel=\'nofollow\' href=\'../html/DL.html\' target=\'_blank\' class=\'nsglogin\'>请登录</a>");
document.writeln("                    <a rel=\'nofollow\' href=\'../html/ZhuCe.html\' target=\'_blank\'>免费注册</a>");
document.writeln("                    <a href=\'https://graph.qq.com/oauth2.0/show?which=Login&display=pc&response_type=code&client_id=101477621&redirect_uri=https%3A%2F%2Fsso.e.qq.com%2Fpassport%3Fsso_redirect_uri%3Dhttp%253A%252F%252Funion.qq.com%252F%26service_tag%3D14&scope=get_user_info\'");
document.writeln("                        title=\'QQ账号登录\' class=\'qq\'>用QQ账号登录</a>");
document.writeln("                    <a href=\'\' title=\'新浪微博\' class=\'sina\'>用微博账号登录</a>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <!-- 搜索 -->");
document.writeln("        <div class=\'header-center\'>");
document.writeln("            <div class=\'content\'>");
document.writeln("                <div class=\'log\'><img src=\'../images/log.png\' alt=\'\'></div>");
document.writeln("                <div class=\'love\'><img src=\'../images/love.gif\' alt=\'\'></div>");
document.writeln("                <div class=\'header-search\'>");
document.writeln("                    <div class=\'search\'>");
document.writeln("                        <ul class=\'tab\'>");
document.writeln("                            <li>商品</li>");
document.writeln("                            <li>店铺</li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                    <form class=\'search-form\' method=\'get\' action=\'https://www.nanshig.com/shop\'>");
document.writeln("                        <input type=\'hidden\' value=\'search\' id=\'search_act\' name=\'act\'>");
document.writeln("                        <input placeholder=\'搜“型男”试试，新品上线，快来拔草\' name=\'keyword\' id=\'keyword\' type=\'text\' class=\'input-text\' value=\'\' maxlength=\'60\' x-webkit-speech=\'\' lang=\'zh-CN\' onwebkitspeechchange=\'foo()\' x-webkit-grammar=\'builtin:search\'>");
document.writeln("                        <input type=\'submit\' id=\'button\' value=\'搜索\' class=\'input-submit\'>");
document.writeln("                    </form>");
document.writeln("                </div>");
document.writeln("                <div class=\'cot\'>热门搜索：");
document.writeln("                    <ul class=\'nav1\'>");
document.writeln("                        <li><a href=\'https://www.nanshig.com/shop/index.php?act=search&amp;op=index&amp;keyword=%E6%BD%AE%E7%94%B7\'>潮男</a>");
document.writeln("                        </li>");
document.writeln("                        <li><a href=\'https://www.nanshig.com/shop/index.php?act=search&amp;op=index&amp;keyword=%E5%A4%96%E5%A5%97\'>外套</a>");
document.writeln("                        </li>");
document.writeln("                        <li><a href=\'https://www.nanshig.com/shop/index.php?act=search&amp;op=index&amp;keyword=%E4%B8%83%E5%88%86%E8%A3%A4\'>七分裤</a>");
document.writeln("                        </li>");
document.writeln("                        <li><a href=\'https://www.nanshig.com/shop/index.php?act=search&amp;op=index&amp;keyword=t%E6%81%A4\'>t恤</a>");
document.writeln("                        </li>");
document.writeln("                        <li><a href=\'https://www.nanshig.com/shop/index.php?act=search&amp;op=index&amp;keyword=%E8%A1%AC%E8%A1%AB\'>衬衫</a>");
document.writeln("                        </li>");
document.writeln("                        <li><a href=\'https://www.nanshig.com/shop/index.php?act=search&amp;op=index&amp;keyword=%E9%A6%99%E6%B0%B4\'>香水</a>");
document.writeln("                        </li>");
document.writeln("                        <li><a href=\'https://www.nanshig.com/shop/index.php?act=search&amp;op=index&amp;keyword=%E5%B8%86%E5%B8%83%E9%9E%8B\'>帆布鞋</a>");
document.writeln("                        </li>");
document.writeln("                        <li><a href=\'https://www.nanshig.com/shop/index.php?act=search&amp;op=index&amp;keyword=%E8%BF%90%E5%8A%A8%E4%BC%91%E9%97%B2\'>运动休闲</a>");
document.writeln("                        </li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <!--导航 -->");
document.writeln("        <nav class=\'nav2\'>");
document.writeln("            <div class=\'nav2-center\'>");
document.writeln("                <div class=\'all\'>");
document.writeln("                    <div class=\'title\'>");
document.writeln("                        <h3><a href=\'https://www.nanshig.com/shop/category.html\'>所有分类</a></h3>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <ul class=\'nav3\'>");
document.writeln("                    <li><a href=\'\'>首页</a></li>");
document.writeln("                    <li><a href=\'../html/list.html\'>潮款服装</a></li>");
document.writeln("                    <li><a href=\'\'>时尚鞋靴</a></li>");
document.writeln("                    <li><a href=\'\'>护肤美妆</a></li>");
document.writeln("                    <li><a href=\'\'>精选套装</a></li>");
document.writeln("                    <li><a href=\'\'>时尚T恤</a></li>");
document.writeln("                    <li><a href=\'\'>防晒衣</a></li>");
document.writeln("                    <li><a href=\'\'>POLO衫</a></li>");
document.writeln("                    <li><a href=\'\'>休闲鞋</a></li>");
document.writeln("                    <li><a href=\'\'>百搭七分裤</a></li>");
document.writeln("                </ul>");
document.writeln("                <div class=\'XiaZai\'><a href=\'\' target=\'_blank\'>下载APP</a></div>");
document.writeln("            </div>");
document.writeln("        </nav>");
document.writeln("    </div>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");