document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'ie=edge\'>");
document.writeln("    <title>Document</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("    <div id=\'side-column\'>");
document.writeln("        <div class=\'side-mid\'>");
document.writeln("            <div class=\'side-mid-top\'>");
document.writeln("                <div>");
document.writeln("                    <em></em>");
document.writeln("                    <span>我的账户</span>");
document.writeln("                </div>");
document.writeln("                <img src=\'https://www.nanshig.com/data/upload/shop/common/default_user_portrait.gif\' alt=\'\'>");
document.writeln("            </div>");
document.writeln("            <div class=\'side-car\'>");
document.writeln("                <i></i>");
document.writeln("                <span>购物车</span>");
document.writeln("                <div class=\'numcar\'></div>");
document.writeln("            </div>");
document.writeln("            <span>");
document.writeln("                <div>");
document.writeln("                    <em></em>");
document.writeln("                    <span>在线联系</span>");
document.writeln("        </div>");
document.writeln("        </span>");
document.writeln("        <span>");
document.writeln("                <div>");
document.writeln("                    <em></em>");
document.writeln("                    <span>商品对比</span>");
document.writeln("    </div>");
document.writeln("    </span>");
document.writeln("    </div>");
document.writeln("    <span class=\'to-top\'>");
document.writeln("            <div>");
document.writeln("                <em></em>");
document.writeln("                <span>返回顶部</span>");
document.writeln("    </div>");
document.writeln("    </span>");
document.writeln("    </div>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");