document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'ie=edge\'>");
document.writeln("    <title>Document</title>");
document.writeln("    <link rel=\'stylesheet\' href=\'../css/foot.css\'>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("    <div class=\'foot\'>");
document.writeln("        <div class=\'foot-top\'>");
document.writeln("            <div class=\'foot-top-center\'>");
document.writeln("                <img src=\'../images/nsgfoot_bz.png\' alt=\'\' width=\'1200\' height=\'90\'>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'foot-bottom\'>");
document.writeln("            <div class=\'bottom-box\'>");
document.writeln("                <div class=\'bottom-box-left\'>");
document.writeln("                    <div class=\'bottom-box-img\'></div>");
document.writeln("                    <p>男士购客服</p>");
document.writeln("                    <p>添加微信号</p>");
document.writeln("                </div>");
document.writeln("                <div class=\'bottom-box-center\'>");
document.writeln("                    <ul class=\'box-center\'>");
document.writeln("                        <li>");
document.writeln("                            <h3>新手指南</h3>");
document.writeln("                            <a href=\'https://www.nanshig.com/shop/article-18.html\' target=\'_blank\'>找回密码</a>");
document.writeln("                            <a href=\'https://www.nanshig.com/shop/article-6.html\' target=\'_blank\'>注册账号</a>");
document.writeln("                            <a href=\'https://www.nanshig.com/shop/article-44.html\' target=\'_blank\'>交易条款</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <h3>支付配送</h3>");
document.writeln("                            <a href=\'https://www.nanshig.com/shop/article-17.html\' target=\'_blank\'>网上支付</a>");
document.writeln("                            <a href=\'https://www.nanshig.com/shop/article-42.html\' target=\'_blank\'>配送运费</a>");
document.writeln("                            <a href=\'https://www.nanshig.com/shop/article-43.html\' target=\'_blank\'>配送方式</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <h3>售后服务</h3>");
document.writeln("                            <a href=\'https://www.nanshig.com/shop/article-31.html\' target=\'_blank\'>售后政策</a>");
document.writeln("                            <a href=\'https://www.nanshig.com/shop/article-32.html\' target=\'_blank\'>售后流程</a>");
document.writeln("                            <a href=\'https://www.nanshig.com/shop/article-34.html\' target=\'_blank\'>售后申请</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <h3>关于我们</h3>");
document.writeln("                            <a href=\'https://www.nanshig.com/shop/article-22.html\' target=\'_blank\'>公司介绍</a>");
document.writeln("                            <a href=\'https://www.nanshig.com/shop/article-23.html\' target=\'_blank\'>隐私声明</a>");
document.writeln("                            <a href=\'https://www.nanshig.com/shop/article-24.html\' target=\'_blank\'>招贤纳士</a>");
document.writeln("                        </li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <div class=\'bottom-box-right cfix\'>");
document.writeln("                    <div class=\'contact-us\'>");
document.writeln("                        <h3>联系我们</h3>");
document.writeln("                        <p>客服微信：gebuzaishuai</p>");
document.writeln("                        <p>工作日：9:00-20:00</p>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'attention-us cfix\'>");
document.writeln("                        <h3>关注我们</h3>");
document.writeln("                        <div class=\'weiXin\' onclick=\'window.open(\'https://www.nanshig.com/weixin/\');\' title=\'男士购微信\'>");
document.writeln("                            <div class=\'weiXinCode\'></div>");
document.writeln("                        </div>");
document.writeln("                        <div class=\'weiBo\' onclick=\'window.open(\'https://weibo.com/p/1006065678617328\');\' title=\'男士购微博\'>");
document.writeln("                            <div class=\'weiBoCode\'></div>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");